POST http://localhost:3000/patients HTTP/1.1
Content-Type: application/json

{
    "id": "",
    "name": "Levent", 
    "surname:":"Arslan", 
    "gender":"Male", 
    "phone": "+(90)555-555-55-55",
    "email":"ceyhunarslan@gmail.com", 
    "password":"asfsdgsgsdfg", 
    "appointments": []
}